version: '3'

services:
  node:
    container_name: node

    build: 
     context: .
     dockerfile: Dockerfile

    command: sh -c "npm start"
    
    volumes:
      - ./react-app:/usr/src/app
        
    ports:
      - '3000:3000'
      
volumes:
  node_modules_volume:   