version: '3'

services:
  db:
    container_name: db    
    image: mysql
    build:
     context: .
    volumes:
     - ./db/init:/docker-entrypoint-initdb.d
    environment:
     - MYSQL_ROOT_PASSWORD=root

  







